#!/bin/sh

echo committing as $(git config user.name)
git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read line; do vendor/bin/ecs check "$line" --fix --quiet; git add "$line"; done
